### ISSUE TITLE
意味不明的 all_utt

### ISSUE THREAD

**Issue by Droidtown** [joehuangx/LokiHub#11]
https://github.com/joehuangx/LokiHub/blob/a6bea077b73ab10e5e88596db9fa2b856f6e7c23/IngredientBot/intent/Loki_InSeason.py#L76

這一段裡的 all_utt 是什麼意思，我看不太明白。
此外，這個 block 裡的 `[芭樂]有什麼禁忌` 中的「芭樂」是怎麼取得被括起來的結果的呢？

**Comment by joehuangx** [comment]
主要是想處理一個句子結構對應到多種intent的情況，
例如：「有什麼禁忌」會對應到 InSeason, reject, taboo 三種intent，而正確的 intent 為 taboo。
> [InSeason] 有什麼禁忌 ===> 有什麼[水果]
> [reject] 有什麼禁忌 ===> 有甚麼[別]的[食材]
> [taboo] 有什麼禁忌 ===> 有什麼禁忌 

處理的邏輯是這樣寫的：
1. 在 runLoki 裡，將 inputSTR 對應到的所有 utterance 存在 all_utt 中：
https://github.com/joehuangx/LokiHub/blob/de105b2afaebb2d2270286773900ea8c361587a9/IngredientBot/ingredientBot.py#L157-L161

2. 接著將 all_utt 隨其他參數一併傳給 getResult：
https://github.com/joehuangx/LokiHub/blob/de105b2afaebb2d2270286773900ea8c361587a9/IngredientBot/ingredientBot.py#L169

3.在 getResult 裡，如果 inputSTR 的 utterance == "有什麼[水果]" ，同時 "有什麼禁忌" 也在 all_utt 時，把原本已加入的 inseason 去掉，讓回傳的 resultDICT 中不會有 inseason 這個 intent。
https://github.com/joehuangx/LokiHub/blob/a6bea077b73ab10e5e88596db9fa2b856f6e7c23/IngredientBot/intent/Loki_InSeason.py#L75-L77

**Comment by Droidtown** [comment]
[InSeason] 有什麼禁忌 ===> 有什麼[水果]
[reject] 有什麼禁忌 ===> 有甚麼[別]的[食材]
這兩段如果用... 
```python
if args[0] != 禁忌:
    blah blah blah
```
和
```python
if args[1] != 禁忌:
    blah blah blah
```
來處理呢？

**Comment by joehuangx** [comment]
Wow, 這方法可以處理我的問題！

但剛遇到一個狀況：
「有甚麼紫甘藍的作法」對應到 `有什麼[水果]` & `有甚麼[紫甘藍]的作法`
> [InSeason] 有甚麼紫甘藍的作法 ===> 有什麼[水果]
> [recipe] 有甚麼紫甘藍的作法 ===> 有甚麼[紫甘藍]的作法

`if utterance == "有什麼[水果]":` 時，args[0] 會是紫甘藍，但紫甘藍剛好是變數，目前卡住在這邊。

**Comment by Droidtown** [comment]
[InSeason] 裡的 args[0]，是不是只有「水果、食材、海鮮」三種可能？
如果是的話，那麼只要：
```python
#[InSeason]
if utterance == "有什麼[水果]":
    if args[0] in ("水果", "食材", "海鮮"):
        #Do_something_here
    else:
        pass
```
這樣就能讓「紫甘藍」(還是紫甘籃？)走上 'pass' 的路徑了。

**Comment by joehuangx** [comment]
謝謝！目前已經全部換成這樣的方式處理了。
另外某些過短的句子 ( 如："還有呢" ) 、或是與過多句子衝突的句子 ( 如："所有當季食材" ) 改成用直接對應的方式來判斷 intent。
